ninecats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests
end

ninecats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninecats/app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = ['Black', 'Orange','White','Speckled']

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, length: { is: 1 }

  has_many :cat_rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  
end

ninecats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUS = ['APPROVED', 'DENIED', 'PENDING']
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: STATUS }
  validate :does_not_overlap_approved_requests

  belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat

  has_many :cat_rental_requests,
    through: :cat,
    source: :cat_rental_requests

  def overlapping_requests

    cat_rental_requests
      .where("start_date <= '#{self.end_date}'")
      .where("end_date >= '#{self.start_date}'")
    #where other start dates is before our end date
    #where other end dates are after our start date
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def does_not_overlap_approved_requests
    if overlapping_approved_requests.exists?
      errors[:body] << "You can't have that cat!"
    end
  end

  def inspect
    "<ID: #{self.cat_id} Start Date:#{self.start_date} End Date: #{self.end_date} Status: #{self.status}>\n"
  end
end

ninecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

ninecats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    def new
      @request = CatRentalRequest.new
      @cats = Cat.all
      render :new
    end

    def create
      @request = CatRentalRequest.new(request_params)

      if @request.save
        redirect_to cat_url(@request.cat_id)
      else
        render json: @request.errors.full_messages
      end
    end

    def request_params
      params.require(:request).permit(:cat_id, :start_date, :end_date)
    end


end

ninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    @requests = @cat.cat_rental_requests.order('start_date')
    render :show
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  def new
    @cat = Cat.new

    render :new
  end



  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end


  end

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :description, :sex)
  end
end

ninecats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninecats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

ninecats/app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

ninecats/app/helpers/cats_helper.rb
module CatsHelper
end

ninecats/app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="POST">
  <select name="request[cat_id]">
    <option value="" disabled="disabled"> -- </option>
    <% @cats.each do |cat| %>
        <option value="<%=cat.id%>"> <%=cat.name%> </option>
    <% end %>
  </select>

  <input type="date" name="request[start_date]" value="<%= @request.start_date %>">
  <input type="date" name="request[end_date]" value="<%= @request.end_date %>">

  <input type="submit" value="Rent a Cat!"/>

</form>

ninecats/app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% persisted = true %>
  <form action="<%= cat_url(cat) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH" />
<% else  %>
  <% persisted = false %>
  <form action="<%= cats_url %>" method="POST">
<% end %>

  <input type="text" name="cat[name]" value="<%= cat.name %>"/>

  <input type="radio" id="male" name="cat[sex]" value="M" <%= cat.sex == 'M' ? "checked" : "" %> />
  <label for="male">M</label>
  <input type="radio"id="female" name="cat[sex]" value="F" <%= cat.sex == 'F' ? "checked" : "" %>/>
  <label for="female">F</label>

  <select name="cat[color]">
    <option value="" disabled="disabled"> -- </option>
    <% Cat::COLORS.each do |color| %>
      <% if cat.color == color %>
        <option value="<%=color%>" selected="true" > <%=color%> </option>
      <% else %>
        <option value="<%=color%>" > <%=color%> </option>
      <% end %>
    <% end %>
  </select>

  <input id="birthdate" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  <textarea name="cat[description]" rows="10" cols="50" ><%= cat.description %></textarea>
  <input type="submit" value="<%= persisted ? "Update Cat!" : "Create Cat!" %>"/>
</form>

ninecats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat%>

ninecats/app/views/cats/index.html.erb
  <% @cats.each do |cat| %>
    <ul>
      <li> <%= link_to cat.name, cat_url(cat) %> </li>
    </ul>
  <% end %>

ninecats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat%>

<!-- <form action="<%= cats_url %>" method="POST">
  <input type="text" name="cat[name]"/>

  <input type="radio" id="male" name="cat[sex]" value="M" />
  <label for="male">M</label>
  <input type="radio"id="female" name="cat[sex]" value="F" />
  <label for="female">F</label>

  <select name="cat[color]">
    <option value="" selected="true" disabled="disabled"> </option>
    <% Cat::COLORS.each do |color| %>
     <option value="<%=color%>"> <%=color%> </option>
    <% end %>
  </select>

  <input id="birthdate" type="date" name="cat[birth_date]">
  <textarea name="cat[description]" rows="10" cols="50"> Description </textarea>
  <input type="submit" value="Create Cat!" />

</form> -->

ninecats/app/views/cats/show.html.erb
<!-- :birth_date, :color, :name, :sex, :description -->
<table>
  <tr>
    <th> Name </th>
    <th> Birthdate </th>
    <th> Color </th>
    <th> Sex </th>
    <th> Description</th>
  </tr>
  <tr>
    <td> <%= @cat.name %> </td>
    <td> <%= @cat.birth_date %> </td>
    <td> <%= @cat.color %> </td>
    <td> <%= @cat.sex %> </td>
    <td> <%= @cat.description %> </td>
  </tr>
</table>
<h3> Currently Rented On </h3>
<table>
  <tr>
    <th> Start Date </th>
    <th> End Date </th>
  </tr>
    <% @requests.each do |request| %>
      <tr>
        <td> <%= request.start_date %> </td>
        <td> <%= request.end_date %> </td>
      </tr>
    <% end %>
</table>

ninecats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninecats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>